//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Builder.rc
//
#define IDC_MYICON                      2
#define IDD_TOOLBOX                     9
#define IDD_BUILDER_DIALOG              102
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_BUILDER                     107
#define IDC_BUILDER                     109
#define IDR_MAINFRAME                   128
#define IDD_LIGHTING                    131
#define IDD_GRASS                       132
#define IDD_MOPRHING                    133
#define IDD_MORPHING                    133
#define IDD_TEXTURES                    134
#define IDD_TERRAIN                     135
#define IDD_LIQUIDS                     136
#define IDD_PROGRESS_DIALOG             143
#define IDD_OBJECTS                     144
#define IDD_MODELS                      144
#define IDD_DETAILS                     146
#define IDD_CUBEMAP                     147
#define IDD_CLOUD                       148
#define IDB_BITMAP1                     154
#define ID_CHILD                        201
#define IDC_ADD_LIGHT                   1000
#define IDB_WRENCH                      1000
#define IDC_LIGHT_CHECK                 1001
#define IDC_LIGHTING_GROUP              1002
#define IDC_ENABLE_LIGHT_CHECK          1003
#define IDC_REMOVE_LIGHT                1004
#define IDC_TERRAIN                     1005
#define IDC_DETAIL                      1006
#define IDC_LOAD_TERRAIN                1007
#define IDC_TERRAIN_RELOAD              1007
#define IDC_REMOVE_TERRAIN              1008
#define IDC_LOAD_DETAIL                 1009
#define IDC_DETAIL_RELOAD               1009
#define IDC_REMOVE_DETAIL               1011
#define IDC_PLACE_DETAIL                1012
#define IDC_CLEAR                       1013
#define IDC_TERRAIN_COMBO               1014
#define IDC_DETAIL_COMBO                1015
#define IDC_TERRAIN_LAYER_COMBO         1015
#define IDC_REMOVE_ALL_DETAILS          1016
#define IDC_STATIC2                     1017
#define IDC_STATIC3                     1018
#define IDC_STATIC4                     1019
#define IDC_STATIC5                     1020
#define IDC_STATIC6                     1021
#define IDC_STATIC7                     1022
#define IDC_STATIC8                     1023
#define IDC_LIQUID_TAB                  1025
#define IDC_STATIC13                    1029
#define IDC_STATIC14                    1030
#define IDC_STATIC1                     1031
#define IDC_STATIC21                    1032
#define IDC_STATIC23                    1032
#define IDC_STATIC101                   1033
#define IDC_RAND_CHECK                  1034
#define IDC_STATIC26                    1035
#define IDC_STATIC103                   1036
#define IDC_STATIC29                    1036
#define IDC_FLAT_CHECK                  1037
#define IDC_STATIC31                    1037
#define IDC_STATIC15                    1038
#define IDC_STATIC30                    1038
#define IDC_STATIC16                    1039
#define IDC_STATIC32                    1039
#define IDC_STATIC17                    1040
#define IDC_STATIC33                    1040
#define IDC_STATIC22                    1041
#define IDC_SPEED_EDIT                  1042
#define IDC_RAND_EDIT                   1043
#define IDC_STATIC18                    1044
#define IDC_Z_EDIT                      1045
#define IDC_X_EDIT                      1046
#define IDC_STATIC19                    1047
#define IDC_SPEED_EDIT2                 1047
#define IDC_SINUS_EDIT                  1047
#define IDC_TEXT_X_EDIT                 1048
#define IDC_STATIC20                    1049
#define IDC_TEXT_Z_EDIT                 1050
#define IDC_LOAD_GRASS                  1052
#define IDC_GRASS_RELOAD                1052
#define IDC_FILL_GRASS                  1053
#define IDC_GRASS_FILL                  1053
#define IDC_GRASS_COMBO                 1054
#define IDC_REMOVE_GRASS                1055
#define IDC_CLEAR_GRASS                 1056
#define IDC_GRASS_CLEAR                 1056
#define IDC_GRASS_SIZE                  1057
#define IDC_STATIC24                    1058
#define IDC_STATIC100                   1059
#define IDC_GRASS_DENSITY               1060
#define IDC_STATIC25                    1061
#define IDC_GRASS_SIZE2                 1061
#define IDC_GRASS_X_EDIT                1062
#define IDC_STATIC250                   1063
#define IDC_GRASS_DENSITY2              1063
#define IDC_STATIC27                    1064
#define IDC_STATIC102                   1065
#define IDC_GRASS_Z_EDIT                1066
#define IDC_GRASS_HEIGHT                1067
#define IDC_GRASS                       1068
#define IDC_GRASS_HEIGHT2               1068
#define IDC_LOAD_LIQUID                 1069
#define IDC_STATIC117                   1069
#define IDC_LIQUID_RELOAD               1069
#define IDC_FILL_LIQUID                 1070
#define IDC_STATIC118                   1070
#define IDC_LIQUID_PLACE                1070
#define IDC_LIQUID_COMBO                1071
#define IDC_STATIC119                   1071
#define IDC_REMOVE_LIQUID               1072
#define IDC_CLEAR_LIQUID                1073
#define IDC_LIQUID_CLEAR                1073
#define IDC_STATIC104                   1074
#define IDC_LIQUID_SPEED                1075
#define IDC_STATIC105                   1076
#define IDC_GRASS_CHECK                 1078
#define IDC_GRASS_PIC                   1079
#define IDC_LIQUID_PIC                  1081
#define IDC_STATIC106                   1082
#define IDC_STATIC201                   1083
#define IDC_LIQUID_ALPHA                1084
#define IDC_LIQUID_MAX                  1085
#define IDC_STATIC111                   1086
#define IDC_LIQUID_MIN                  1087
#define IDC_LIQUID_CHECK                1088
#define IDC_STATIC107                   1089
#define IDC_LIQUID_TYPE_COMBO           1091
#define IDC_AMB_R_SLIDER                1092
#define IDC_STATIC112                   1093
#define IDC_AMB_B_SLIDER                1093
#define IDC_LIQUID_STRETCHY             1094
#define IDC_STATIC116                   1094
#define IDC_AMB_G_SLIDER                1094
#define IDC_LIQUID_MAX_SLIDER           1094
#define IDC_STATIC108                   1095
#define IDC_DIFF_R_SLIDER               1095
#define IDC_LIQUID_MIN_SLIDER           1095
#define IDC_DETAIL_ALPHA_SLIDER         1095
#define IDC_LIQUID_STORMY               1096
#define IDC_DIFF_B_SLIDER               1096
#define IDC_DETAIL_CHECK                1096
#define IDC_STATIC113                   1097
#define IDC_DIFF_G_SLIDER               1097
#define IDC_LIQUID_SPEED_SLIDER         1097
#define IDC_SPEC_R_SLIDER               1098
#define IDC_LIQUID_STORMY_SLIDER        1098
#define IDC_STATIC28                    1099
#define IDC_SPEC_B_SLIDER               1099
#define IDC_STATIC115                   1100
#define IDC_SPEC_G_SLIDER               1100
#define IDC_LIQUID_ALPHA_SLIDER         1100
#define IDC_STATIC114                   1101
#define IDC_TYPE_COMBO                  1102
#define IDC_SLIDER1                     1103
#define IDC_LIQUID_WAVE_SLIDER          1103
#define IDC_TERRAIN_HEIGHT_SLIDER       1103
#define IDC_MODEL_SCALE_SLIDER          1103
#define IDC_DETAIL_BLUE_SLIDER          1103
#define IDC_LIQUID_WAVE                 1104
#define IDC_DETAIL_GREEN_SLIDER         1104
#define IDC_GRASS_GREEN_SLIDER          1104
#define IDC_DETAIL_RED_SLIDER           1105
#define IDC_GRASS_RED_SLIDER            1105
#define IDC_LIQUID_STRETCH              1106
#define IDC_GRASS_ALPHA_SLIDER          1106
#define IDC_LIQUID_STRETCH_SLIDER       1107
#define IDC_GRASS_BLUE_SLIDER           1107
#define IDC_LIQUID_Z_DIR_SLIDER         1108
#define IDC_LIQUID_X_DIR_SLIDER         1109
#define IDC_TERRAIN_HEIGHT              1113
#define IDC_TERRAIN_AFFECT_CHECK        1114
#define IDC_TERRAIN_MAP_SCALE_SLIDER    1115
#define IDC_TERRAIN_MAP_SCALE           1117
#define IDC_TERRAIN_MAP_X_SLIDER        1118
#define IDC_TERRAIN_MAP_X               1119
#define IDC_TERRAIN_MAP_Z_SLIDER        1120
#define IDC_TERRAIN_MAP_Z               1121
#define IDC_TERRAIN_RESET               1122
#define IDC_TERRAIN_EQUILIZE            1122
#define IDC_TERRAIN_MAX_HEIGHT_SLIDER   1123
#define IDC_TERRAIN_MAX_HEIGHT          1124
#define IDC_TERRAIN_MIN_HEIGHT_SLIDER   1125
#define IDC_TERRAIN_MIN_HEIGHT          1126
#define IDC_TERRAIN_ADJUST              1128
#define IDC_TERRAIN_DROP_CHECK          1129
#define IDC_PROGRESS_BAR                1130
#define IDC_MODEL_COMBO                 1131
#define IDC_MODEL_LOAD                  1132
#define IDC_MODEL_RELOAD                1132
#define IDC_MODEL_PLACE_MODEL           1133
#define IDC_MODEL_REMOVE_ALL            1134
#define IDC_MODEL_REMOVE                1134
#define IDC_MODEL_OBSTACLE_CHECK        1135
#define IDC_MODEL_SCALE                 1136
#define IDC_MODEL_PIC                   1137
#define IDC_MODEL_EXECUTE_SCALE         1138
#define IDC_MODEL_RED_SLIDER            1139
#define IDC_MODEL_GREEN_SLIDER          1140
#define IDC_MODEL_BLUE_SLIDER           1141
#define IDC_MODEL_RED                   1142
#define IDC_MODEL_GREEN                 1143
#define IDC_EDIT4                       1144
#define IDC_MODEL_BLUE                  1144
#define IDC_MODEL_TEXTURE_COMBO         1145
#define IDC_MODEL_RELOAD_TEXTURE        1148
#define IDC_MODEL_ALPHA_SLIDER          1149
#define IDC_MODEL_ALPHA                 1150
#define IDC_DETAIL_BLUE                 1153
#define IDC_DETAIL_ALPHA                1154
#define IDC_DETAIL_GREEN                1155
#define IDC_DETAIL_RED                  1156
#define IDC_SET_LAYER                   1157
#define IDC_CUBEMAP                     1158
#define IDC_LAYER_UP                    1158
#define IDC_CUBEMAP_CHECK               1159
#define IDC_REMOVE_LAYER                1159
#define IDC_CUBEMAP_RED                 1160
#define IDC_LAYER_DOWN                  1160
#define IDC_CUBEMAP_GREEN               1161
#define IDC_CUBEMAP_BLUE                1162
#define IDC_CUBEMAP_ALPHA               1163
#define IDC_CUBEMAP_ALPHA_SLIDER        1164
#define IDC_CUBEMAP_BLUE_SLIDER         1165
#define IDC_CUBEMAP_GREEN_SLIDER        1166
#define IDC_CUBEMAP_RED_SLIDER          1167
#define IDC_CUBEMAP_COMBO               1168
#define IDC_CUBEMAP_RELOAD              1169
#define IDC_CLOUD                       1170
#define IDC_CLOUD_COMBO                 1171
#define IDC_CLOUD_RELOAD                1172
#define IDC_CLOUD_CHECK                 1173
#define IDC_CLOUD_RED                   1174
#define IDC_CLOUD_GREEN                 1175
#define IDC_CLOUD_BLUE                  1176
#define IDC_CLOUD_ALPHA                 1177
#define IDC_CLOUD_ALPHA_SLIDER          1178
#define IDC_CLOUD_BLUE_SLIDER           1179
#define IDC_CLOUD_GREEN_SLIDER          1180
#define IDC_CLOUD_RED_SLIDER            1181
#define IDC_CLOUD_HEIGHT                1182
#define IDC_CLOUD_HEIGHT_SLIDER         1183
#define IDC_CLOUD_Z_DIR_SLIDER          1184
#define IDC_CLOUD_X_DIR_SLIDER          1185
#define IDC_CLOUD_SPEED                 1186
#define IDC_LIQUID_Z                    1186
#define IDC_CLOUD_SPEED_SLIDER          1187
#define IDC_LIQUID_X                    1187
#define IDC_CLOUD_SPREAD                1188
#define IDC_SOLID_BRUSH_CHECK           1188
#define IDC_CLOUD_SPREAD_SLIDER         1189
#define IDC_TEXTURE_CHECK               1189
#define IDC_HIDE_CHECK                  1190
#define IDC_TERRAIN_ALPHA               1193
#define IDC_TERRAIN_ALPHA_SLIDER        1196
#define IDC_AMB_R                       2001
#define IDC_AMB_G                       2002
#define IDC_AMB_B                       2003
#define IDC_DIFF_R                      2004
#define IDC_DIFF_G                      2005
#define IDC_DIFF_B                      2006
#define IDC_MAIN_TOOLS                  10000
#define IDC_TAB                         10001
#define IDC_PLANT                       10002
#define IDC_WEED                        10003
#define IDC_PAINT                       10004
#define IDC_RUBBER                      10005
#define IDC_MORPH                       10006
#define IDC_NET_CHECK                   10007
#define IDC_TEXT_CHECK                  10008
#define IDC_ROUND_CHECK                 10009
#define IDM_SAVEAS                      32772
#define IDM_SAVE                        32773
#define ID_FILE_SAVE                    32774
#define ID_FILE_LOAD                    32775
#define IDM_LOAD                        32776
#define IDM_NEW                         32777
#define IDC_GRASS_ALPHA                 38303
#define IDC_GRASS_BLUE                  38304
#define IDC_GRASS_GREEN                 38305
#define IDC_GRASS_RED                   38306
#define IDC_GRASS_CHECK2                53921
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1197
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
